FROM mcr.microsoft.com/devcontainers/cpp:1-ubuntu-24.04

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    build-essential \
    cmake \
    git \
    libpq-dev \
    libpqxx-dev \
    libhiredis-dev \
    libasio-dev \
    libssl-dev \
    libsodium-dev

WORKDIR /app

COPY . .

RUN cmake -B build -S . && cmake --build build

CMD ["./build/pixel_server", "8080"]
