events {
    # Maximum number of simultaneous connections per worker
    worker_connections 1024;
}

http {
    access_log /var/log/nginx/access.log;
    # REQUIRED: Tells the browser how to render your CSS properly
    include /etc/nginx/mime.types;

    # The Load Balancer (Round Robin by default)
    upstream backend_servers {
        # max_fails=1: Give up after 1 failed attempt
        # fail_timeout=2s: Keep it marked as "dead" for 2 seconds before checking again
        server backend1:8080 max_fails=1 fail_timeout=2s;
        server backend2:8080 max_fails=1 fail_timeout=2s;
    }

    server {
        # Listen on standard HTTP port
        listen 80;

        # If the dead container doesn't answer within 2 seconds, switch to the survivor
        proxy_connect_timeout 2s; 
        proxy_next_upstream error timeout invalid_header http_500;

        # Route Standard HTTP Traffic (HTML, JS, CSS) directly via Nginx
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Route API Auth/Data Traffic to C++ Backends
        location /login {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /register {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /canvas {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route WebSocket Traffic (CRITICAL)
        location /ws {
            proxy_pass http://backend_servers;
            
            # These headers tell Nginx to "upgrade" the HTTP connection to a WebSocket
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            
            proxy_set_header Host $host;
            
            # Prevent Nginx from closing the connection if a user doesn't click for a while
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }
    }
}